[package]
name = "kalesa"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
image = { version = "0.25", default-features = false, features = ["ico", "png", "bmp"] }
pelite = "0.10"
log = "0.4"
env_logger = "0.11"
